### ISSUE TITLE
Citation of this data collection

### ISSUE THREAD

**Issue by logstar** [hemberg-lab/public-scrnaseq-datasets#30]
I was wondering how to formally cite this collection of scRNA-seq datasets for academic publication.

Thank you for providing this comprehensive and easy-to-use collection. It saved me a lot of time.

**Comment by wikiselev** [comment]
I think, you could just provide a link to this repo. It's not published anywhere...

**Comment by logstar** [comment]
I see. I will provide a link to this repo in my manuscript. 

Thank you for the reply.
